//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootieWorld.data.ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTeam
    {
        public System.Guid TeamId { get; set; }
        public string Name { get; set; }
        public string NickName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string Postcode { get; set; }
        public string Colours { get; set; }
        public string PhoneNumber { get; set; }
        public string Website { get; set; }
        public Nullable<System.Guid> StadiumID { get; set; }
    
        public virtual tblStadium tblStadium { get; set; }
    }
}
